#!name=Facebook AdBlock

[URL Rewrite]

# Feed
^https:\/\/graph\.facebook\.com\/v\d+\/feed url reject-json

# Stories
^https:\/\/graph\.facebook\.com\/v\d+\/stories url reject-json

# Marketplace
^https:\/\/graph\.facebook\.com\/v\d+\/marketplace url reject-json

# Ads
^https:\/\/graph\.facebook\.com\/v\d+\/ads url reject