#!name=Instagram AdBlock

[URL Rewrite]

# Feed广告
^https:\/\/i\.instagram\.com\/api\/v\d+\/feed\/timeline\/ url reject-json

# Reels广告
^https:\/\/i\.instagram\.com\/api\/v\d+\/clips\/viewer\/ url reject-json

# Explore
^https:\/\/i\.instagram\.com\/api\/v\d+\/discover\/explore\/ url reject-json

# 推荐
^https:\/\/i\.instagram\.com\/api\/v\d+\/friendships\/suggestions\/ url reject-json