#!name=Meta Core
#!desc=基础代理 + 追踪拦截

[MITM]
hostname = %APPEND% i.instagram.com, graph.instagram.com, graph.facebook.com

[Rule]

DOMAIN-SUFFIX,instagram.com,PROXY
DOMAIN-SUFFIX,facebook.com,PROXY
DOMAIN-SUFFIX,fbcdn.net,PROXY
DOMAIN-SUFFIX,fbsbx.com,PROXY
DOMAIN-SUFFIX,messenger.com,PROXY

DOMAIN-SUFFIX,analytics.instagram.com,REJECT
DOMAIN-SUFFIX,connect.facebook.net,REJECT
DOMAIN-SUFFIX,tracking.facebook.com,REJECT
DOMAIN-SUFFIX,ads.facebook.com,REJECT
DOMAIN-SUFFIX,ads.instagram.com,REJECT